// Egyptian Patient Reviews Data for Dr. Ahmed Abdelrahim Abdelatif
const patientReviews = [
    {
        id: 1,
        name: "م. محمود السيد",
        nameEn: "Eng. Mahmoud El-Sayed",
        avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=150",
        avatarInitial: "م",
        city: "القاهرة - مدينة نصر",
        cityEn: "Cairo",
        rating: 5,
        date: "١٢ سبتمبر ٢٠٢٥",
        category: "endodontics",
        treatment: "حشو عصب بدون ألم (Molar RCT)",
        verified: true,
        comment: "دكتور أحمد ما شاء الله عليه شاطر جداً وايده خفيفة جداً! كان عندي وجع رهيب في الدرس وقالي محتاج عصب، والله العظيم عمل العملية في جلسة واحدة ومن غير ما أحس بأي ألم، والتعقيم في العيادة على أعلى مستوى."
    },
    {
        id: 2,
        name: "د. سارة الحسيني",
        nameEn: "Dr. Sarah El-Hosseiny",
        avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=150",
        avatarInitial: "س",
        city: "الزقازيق - الشرقية",
        cityEn: "Zagazig",
        rating: 5,
        date: "٢٨ أغسطس ٢٠٢٥",
        category: "restorative",
        treatment: "حشو تجميلي للأسنان الأمامية (Composite Veneers)",
        verified: true,
        comment: "دكتور أحمد رجعلي ثقتي في الابتسامة! عملي حشو تجميلي لسنّة أمامية مقشورة، النتيجة طبيعية ١٠٠٪ وما حدش يقدر يفرقها عن سناني الأصلية خالص. دكتور محترم ومحترف جداً."
    },
    {
        id: 3,
        name: "أ/ محمد فاروق",
        nameEn: "Mohamed Farouk",
        avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=150",
        avatarInitial: "م",
        city: "العاشر من رمضان",
        cityEn: "10th of Ramadan",
        rating: 5,
        date: "٥ يوليو ٢٠٢٥",
        category: "surgery",
        treatment: "خلع ضرس عقل مدفون (Surgical Extraction)",
        verified: true,
        comment: "كنت مرعوب جداً من موضوع خلع ضرس العقل المدفون بسبب التجارب اللي اسمع عنها، بس دكتور أحمد طمني وشرحلي الخطوات بكل هدوء. الخلع ما خدش ثلث ساعة والورم بعد العملية كان لا يذكر. شكراً يا دكتور!"
    },
    {
        id: 4,
        name: "د./ مريم الشاذلي",
        nameEn: "Mariam El-Shazly",
        avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=150",
        avatarInitial: "م",
        city: "التجمع الخامس - القاهرة",
        cityEn: "New Cairo",
        rating: 5,
        date: "١٥ مايو ٢٠٢٥",
        category: "whitening",
        treatment: "جلسة تبييض وتنظيف جير (Scaling & Whitening)",
        verified: true,
        comment: "النتيجة بعد جلسة التنظيف والتبييض فوق الممتازة! الأسنان رجعت لميعها وبيضا جداً من غير أي حساسية في اللثة. الدكتور مهتم جداً بأدق التفاصيل وبيشرح ازاي تحافظ على أسنانك."
    },
    {
        id: 5,
        name: "أ/ طارق الغريب",
        nameEn: "Tarek Al-Gharieb",
        avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=150",
        avatarInitial: "ط",
        city: "المنصورة",
        cityEn: "Mansoura",
        rating: 5,
        date: "١٠ فبراير ٢٠٢٦",
        category: "endodontics",
        treatment: "علاج عصب وإعادة بناء درس (Endo & Post Core)",
        verified: true,
        comment: "من أحسن وأرقى الدكاترة اللي تعاملت معاهم في مصر. عملي علاج عصب لدرس سفلي دكاترة كتير قالولي هيتخلع، والحمد لله حفظ على الدرس وعمل عليه طربوش تجميلي ممتاز."
    },
    {
        id: 6,
        name: "أ/ نورهان مصطفى",
        nameEn: "Nourhan Mostafa",
        avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=150",
        avatarInitial: "ن",
        city: "الجيزة - الدقي",
        cityEn: "Giza",
        rating: 5,
        date: "٢٢ يناير ٢٠٢٦",
        category: "pediatric",
        treatment: "علاج أسنان الأطفال (Pediatric Pulpotomy)",
        verified: true,
        comment: "روحت بابني عمر (٦ سنوات) وكان خايف جداً وبيصرخ، الدكتور أحمد ماشاء الله عنده طول بال وصبر عجيب مع الأطفال. خلى عمر يضحك وعمل حشو الأطفال بسهولة من غير أي خوف."
    }
];
